const initList = [
  {
    id: 1,
    img: "https://m.media-amazon.com/images/I/51oN63IpplL.jpg",
    type: "trending",
    name: "book name",
    author: "author name",
    price: 25,
    inventory: 300,
    description:
      "Esta historia está pensada para aquellos que son testigos de conflictos y/o bullying, y que necesitan ser valientes para decir “NO” frente a situaciones injustas, y poder frenar una problemática que es preocupante a nivel mundial. Para poder hacerlo, es clave el desarrollo de habilidades socioemocionales que se adquieren en las relaciones interpersonales. Es necesario trabajar la empatía y el compañerismo con los niños desde la primera infancia, para poder prevenir este tipo de",
  },
  {
    id: 2,
    img: "https://m.media-amazon.com/images/I/4133wGkUaRL.jpg",
    type: "trending",
    name: "book name",
    author: "author name",
    price: 25,
    inventory: 300,
    description:
      "Esta historia está pensada para aquellos que son testigos de conflictos y/o bullying, y que necesitan ser valientes para decir “NO” frente a situaciones injustas, y poder frenar una problemática que es preocupante a nivel mundial. Para poder hacerlo, es clave el desarrollo de habilidades socioemocionales que se adquieren en las relaciones interpersonales. Es necesario trabajar la empatía y el compañerismo con los niños desde la primera infancia, para poder prevenir este tipo de",
  },
  {
    id: 3,
    img: "https://m.media-amazon.com/images/I/51E2LCvj1ZL.jpg",
    type: "trending",
    name: "book name",
    author: "author name",
    price: 25,
    inventory: 300,
    description:
      "Esta historia está pensada para aquellos que son testigos de conflictos y/o bullying, y que necesitan ser valientes para decir “NO” frente a situaciones injustas, y poder frenar una problemática que es preocupante a nivel mundial. Para poder hacerlo, es clave el desarrollo de habilidades socioemocionales que se adquieren en las relaciones interpersonales. Es necesario trabajar la empatía y el compañerismo con los niños desde la primera infancia, para poder prevenir este tipo de",
  },
  {
    id: 4,
    img: "https://m.media-amazon.com/images/I/61bPiEPsl4L._AC_SY200_.jpg",
    type: "trending",
    name: "book name",
    author: "author name",
    price: 25,
    inventory: 300,
    description:
      "Esta historia está pensada para aquellos que son testigos de conflictos y/o bullying, y que necesitan ser valientes para decir “NO” frente a situaciones injustas, y poder frenar una problemática que es preocupante a nivel mundial. Para poder hacerlo, es clave el desarrollo de habilidades socioemocionales que se adquieren en las relaciones interpersonales. Es necesario trabajar la empatía y el compañerismo con los niños desde la primera infancia, para poder prevenir este tipo de",
  },
  {
    id: 5,
    img: "https://m.media-amazon.com/images/I/61fmfnA-uCL.jpg",
    type: "trending",
    name: "book name",
    author: "author name",
    price: 25,
    inventory: 300,
    description:
      "Esta historia está pensada para aquellos que son testigos de conflictos y/o bullying, y que necesitan ser valientes para decir “NO” frente a situaciones injustas, y poder frenar una problemática que es preocupante a nivel mundial. Para poder hacerlo, es clave el desarrollo de habilidades socioemocionales que se adquieren en las relaciones interpersonales. Es necesario trabajar la empatía y el compañerismo con los niños desde la primera infancia, para poder prevenir este tipo de",
  },
  {
    id: 6,
    img: "https://m.media-amazon.com/images/I/513Y5o-DYtL.jpg",
    type: "trending",
    name: "book name",
    author: "author name",
    price: 25,
    inventory: 300,
    description:
      "Esta historia está pensada para aquellos que son testigos de conflictos y/o bullying, y que necesitan ser valientes para decir “NO” frente a situaciones injustas, y poder frenar una problemática que es preocupante a nivel mundial. Para poder hacerlo, es clave el desarrollo de habilidades socioemocionales que se adquieren en las relaciones interpersonales. Es necesario trabajar la empatía y el compañerismo con los niños desde la primera infancia, para poder prevenir este tipo de",
  },
  {
    id: 7,
    img: "https://m.media-amazon.com/images/I/51b6fvQr1-L.jpg",
    type: "trending",
    name: "book name",
    author: "author name",
    price: 25,
    inventory: 300,
    description:
      "Esta historia está pensada para aquellos que son testigos de conflictos y/o bullying, y que necesitan ser valientes para decir “NO” frente a situaciones injustas, y poder frenar una problemática que es preocupante a nivel mundial. Para poder hacerlo, es clave el desarrollo de habilidades socioemocionales que se adquieren en las relaciones interpersonales. Es necesario trabajar la empatía y el compañerismo con los niños desde la primera infancia, para poder prevenir este tipo de",
  },
  {
    id: 8,
    img: "https://m.media-amazon.com/images/I/61tBNtQv45L.jpg",
    type: "trending",
    name: "book name",
    author: "author name",
    price: 25,
    inventory: 300,
    description:
      "Esta historia está pensada para aquellos que son testigos de conflictos y/o bullying, y que necesitan ser valientes para decir “NO” frente a situaciones injustas, y poder frenar una problemática que es preocupante a nivel mundial. Para poder hacerlo, es clave el desarrollo de habilidades socioemocionales que se adquieren en las relaciones interpersonales. Es necesario trabajar la empatía y el compañerismo con los niños desde la primera infancia, para poder prevenir este tipo de",
  },
  {
    id: 9,
    img: "https://m.media-amazon.com/images/I/61VgZPzVIBL._AC_SY200_.jpg",
    type: "forYou",
    name: "book name",
    author: "author name",
    price: 25,
    inventory: 300,
    description:
      "Esta historia está pensada para aquellos que son testigos de conflictos y/o bullying, y que necesitan ser valientes para decir “NO” frente a situaciones injustas, y poder frenar una problemática que es preocupante a nivel mundial. Para poder hacerlo, es clave el desarrollo de habilidades socioemocionales que se adquieren en las relaciones interpersonales. Es necesario trabajar la empatía y el compañerismo con los niños desde la primera infancia, para poder prevenir este tipo de",
  },
  {
    id: 10,
    img: "https://m.media-amazon.com/images/I/61aVumIonhL._AC_SY200_.jpg",
    type: "forYou",
    name: "book name",
    author: "author name",
    price: 25,
    inventory: 300,
    description:
      "Esta historia está pensada para aquellos que son testigos de conflictos y/o bullying, y que necesitan ser valientes para decir “NO” frente a situaciones injustas, y poder frenar una problemática que es preocupante a nivel mundial. Para poder hacerlo, es clave el desarrollo de habilidades socioemocionales que se adquieren en las relaciones interpersonales. Es necesario trabajar la empatía y el compañerismo con los niños desde la primera infancia, para poder prevenir este tipo de",
  },
  {
    id: 11,
    img: "https://m.media-amazon.com/images/I/41whMkdjtBL._AC_SY200_.jpg",
    type: "forYou",
    name: "book name",
    author: "author name",
    price: 25,
    inventory: 300,
    description:
      "Esta historia está pensada para aquellos que son tesdivtigos de conflictos y/o bullying, y que necesitan ser valientes para decir “NO” frente a situaciones injustas, y poder frenar una problemática que es preocupante a nivel mundial. Para poder hacerlo, es clave el desarrollo de habilidades socioemocionales que se adquieren en las relaciones interpersonales. Es necesario trabajar la empatía y el compañerismo con los niños desde la primera infancia, para poder prevenir este tipo de",
  },
  {
    id: 12,
    img: "https://m.media-amazon.com/images/I/61mi9uULrLL._AC_SY200_.jpg",
    type: "forYou",
    name: "book name",
    author: "author name",
    price: 25,
    inventory: 300,
    description:
      "Esta historia está pensada para aquellos que son testigos de conflictos y/o bullying, y que necesitan ser valientes para decir “NO” frente a situaciones injustas, y poder frenar una problemática que es preocupante a nivel mundial. Para poder hacerlo, es clave el desarrollo de habilidades socioemocionales que se adquieren en las relaciones interpersonales. Es necesario trabajar la empatía y el compañerismo con los niños desde la primera infancia, para poder prevenir este tipo de",
  },
  {
    id: 13,
    img: "https://m.media-amazon.com/images/I/61aVumIonhL._AC_SY200_.jpg",
    type: "forYou",
    name: "book name",
    author: "author name",
    price: 25,
    inventory: 300,
    description:
      "Esta historia está pensada para aquellos que son testigos de conflictos y/o bullying, y que necesitan ser valientes para decir “NO” frente a situaciones injustas, y poder frenar una problemática que es preocupante a nivel mundial. Para poder hacerlo, es clave el desarrollo de habilidades socioemocionales que se adquieren en las relaciones interpersonales. Es necesario trabajar la empatía y el compañerismo con los niños desde la primera infancia, para poder prevenir este tipo de",
  },
  {
    id: 14,
    img: "https://m.media-amazon.com/images/I/41whMkdjtBL._AC_SY200_.jpg",
    type: "forYou",
    name: "book name",
    author: "author name",
    price: 25,
    inventory: 300,
    description:
      "Esta historia está pensada para aquellos que son testigos de conflictos y/o bullying, y que necesitan ser valientes para decir “NO” frente a situaciones injustas, y poder frenar una problemática que es preocupante a nivel mundial. Para poder hacerlo, es clave el desarrollo de habilidades socioemocionales que se adquieren en las relaciones interpersonales. Es necesario trabajar la empatía y el compañerismo con los niños desde la primera infancia, para poder prevenir este tipo de",
  },
  {
    id: 15,
    img: "https://m.media-amazon.com/images/I/61mi9uULrLL._AC_SY200_.jpg",
    type: "forYou",
    name: "book name",
    author: "author name",
    price: 25,
    inventory: 300,
    description:
      "Esta historia está pensada para aquellos que son testigos de conflictos y/o bullying, y que necesitan ser valientes para decir “NO” frente a situaciones injustas, y poder frenar una problemática que es preocupante a nivel mundial. Para poder hacerlo, es clave el desarrollo de habilidades socioemocionales que se adquieren en las relaciones interpersonales. Es necesario trabajar la empatía y el compañerismo con los niños desde la primera infancia, para poder prevenir este tipo de",
  },
  {
    id: 16,
    img: "https://m.media-amazon.com/images/I/61mi9uULrLL._AC_SY200_.jpg",
    type: "forYou",
    name: "book name",
    author: "author name",
    price: 25,
    inventory: 300,
    description:
      "Esta historia está pensada para aquellos que son testigos de conflictos y/o bullying, y que necesitan ser valientes para decir “NO” frente a situaciones injustas, y poder frenar una problemática que es preocupante a nivel mundial. Para poder hacerlo, es clave el desarrollo de habilidades socioemocionales que se adquieren en las relaciones interpersonales. Es necesario trabajar la empatía y el compañerismo con los niños desde la primera infancia, para poder prevenir este tipo de",
  },
  {
    id: 17,
    img: "https://m.media-amazon.com/images/I/71b7Hy82JpL._AC_SY200_.jpg",
    type: "forYou",
    name: "book name",
    author: "author name",
    price: 25,
    inventory: 300,
    description:
      "Esta historia está pensada para aquellos que son testigos de conflictos y/o bullying, y que necesitan ser valientes para decir “NO” frente a situaciones injustas, y poder frenar una problemática que es preocupante a nivel mundial. Para poder hacerlo, es clave el desarrollo de habilidades socioemocionales que se adquieren en las relaciones interpersonales. Es necesario trabajar la empatía y el compañerismo con los niños desde la primera infancia, para poder prevenir este tipo de",
  },
  {
    id: 18,
    img: "https://m.media-amazon.com/images/I/61199SIEUbL._AC_SY200_.jpg",
    type: "forYou",
    name: "book name",
    author: "author name",
    price: 25,
    inventory: 300,
    description:
      "Esta historia está pensada para aquellos que son testigos de conflictos y/o bullying, y que necesitan ser valientes para decir “NO” frente a situaciones injustas, y poder frenar una problemática que es preocupante a nivel mundial. Para poder hacerlo, es clave el desarrollo de habilidades socioemocionales que se adquieren en las relaciones interpersonales. Es necesario trabajar la empatía y el compañerismo con los niños desde la primera infancia, para poder prevenir este tipo de",
  },
  {
    id: 19,
    img: "https://m.media-amazon.com/images/I/61S3zhCVkPL._AC_SY200_.jpg",
    type: "forYou",
    name: "book name",
    author: "author name",
    price: 25,
    inventory: 300,
    description:
      "Esta historia está pensada para aquellos que son testigos de conflictos y/o bullying, y que necesitan ser valientes para decir “NO” frente a situaciones injustas, y poder frenar una problemática que es preocupante a nivel mundial. Para poder hacerlo, es clave el desarrollo de habilidades socioemocionales que se adquieren en las relaciones interpersonales. Es necesario trabajar la empatía y el compañerismo con los niños desde la primera infancia, para poder prevenir este tipo de",
  },
  {
    id: 20,
    img: "https://m.media-amazon.com/images/I/61wnXwdvIzL._AC_SY200_.jpg",
    type: "forYou",
    name: "book name",
    author: "author name",
    price: 25,
    inventory: 300,
    description:
      "Esta historia está pensada para aquellos que son testigos de conflictos y/o bullying, y que necesitan ser valientes para decir “NO” frente a situaciones injustas, y poder frenar una problemática que es preocupante a nivel mundial. Para poder hacerlo, es clave el desarrollo de habilidades socioemocionales que se adquieren en las relaciones interpersonales. Es necesario trabajar la empatía y el compañerismo con los niños desde la primera infancia, para poder prevenir este tipo de",
  },
  {
    id: 21,
    img: "https://m.media-amazon.com/images/I/51lfB8o5WQL._AC_SY200_.jpg",
    type: "forYou",
    name: "book name",
    author: "author name",
    price: 25,
    inventory: 300,
    description:
      "Esta historia está pensada para aquellos que son testigos de conflictos y/o bullying, y que necesitan ser valientes para decir “NO” frente a situaciones injustas, y poder frenar una problemática que es preocupante a nivel mundial. Para poder hacerlo, es clave el desarrollo de habilidades socioemocionales que se adquieren en las relaciones interpersonales. Es necesario trabajar la empatía y el compañerismo con los niños desde la primera infancia, para poder prevenir este tipo de",
  },
  {
    id: 22,
    img: "https://m.media-amazon.com/images/I/51PWIy1rHUL._MCnd_AC_.jpg",
    type: "Best Sellers",
    name: "book name",
    author: "author name",
    price: 25,
    inventory: 300,
    description:
      "Esta historia está pensada para aquellos que son testigos de conflictos y/o bullying, y que necesitan ser valientes para decir “NO” frente a situaciones injustas, y poder frenar una problemática que es preocupante a nivel mundial. Para poder hacerlo, es clave el desarrollo de habilidades socioemocionales que se adquieren en las relaciones interpersonales. Es necesario trabajar la empatía y el compañerismo con los niños desde la primera infancia, para poder prevenir este tipo de",
  },
  {
    id: 23,
    img: "https://m.media-amazon.com/images/I/51fhH6wWf1L._MCnd_AC_.jpg",
    type: "Best Sellers",
    name: "book name",
    author: "author name",
    price: 25,
    inventory: 300,
    description:
      "Esta historia está pensada para aquellos que son testigos de conflictos y/o bullying, y que necesitan ser valientes para decir “NO” frente a situaciones injustas, y poder frenar una problemática que es preocupante a nivel mundial. Para poder hacerlo, es clave el desarrollo de habilidades socioemocionales que se adquieren en las relaciones interpersonales. Es necesario trabajar la empatía y el compañerismo con los niños desde la primera infancia, para poder prevenir este tipo de",
  },
  {
    id: 24,
    img: "https://m.media-amazon.com/images/I/41V9BGmYTKL._MCnd_AC_.jpg",
    type: "Best Sellers",
    name: "book name",
    author: "author name",
    price: 25,
    inventory: 300,
    description:
      "Esta historia está pensada para aquellos que son testigos de conflictos y/o bullying, y que necesitan ser valientes para decir “NO” frente a situaciones injustas, y poder frenar una problemática que es preocupante a nivel mundial. Para poder hacerlo, es clave el desarrollo de habilidades socioemocionales que se adquieren en las relaciones interpersonales. Es necesario trabajar la empatía y el compañerismo con los niños desde la primera infancia, para poder prevenir este tipo de",
  },

  {
    id: 25,
    img: "https://m.media-amazon.com/images/I/61atv8Q26iL._MCnd_AC_.jpg",
    type: "Best Sellers",
    name: "book name",
    author: "author name",
    price: 25,
    inventory: 300,
    description:
      "Esta historia está pensada para aquellos que son testigos de conflictos y/o bullying, y que necesitan ser valientes para decir “NO” frente a situaciones injustas, y poder frenar una problemática que es preocupante a nivel mundial. Para poder hacerlo, es clave el desarrollo de habilidades socioemocionales que se adquieren en las relaciones interpersonales. Es necesario trabajar la empatía y el compañerismo con los niños desde la primera infancia, para poder prevenir este tipo de",
  },
  {
    id: 26,
    img: "https://m.media-amazon.com/images/I/41y1paqEhmL._MCnd_AC_.jpg",
    type: "Best Sellers",
    name: "book name",
    author: "author name",
    price: 25,
    inventory: 300,
    description:
      "Esta historia está pensada para aquellos que son testigos de conflictos y/o bullying, y que necesitan ser valientes para decir “NO” frente a situaciones injustas, y poder frenar una problemática que es preocupante a nivel mundial. Para poder hacerlo, es clave el desarrollo de habilidades socioemocionales que se adquieren en las relaciones interpersonales. Es necesario trabajar la empatía y el compañerismo con los niños desde la primera infancia, para poder prevenir este tipo de",
  },
  {
    id: 27,
    img: "https://m.media-amazon.com/images/I/51OuvCFwyZL._MCnd_AC_.jpg",
    type: "Best Sellers",
    name: "book name",
    author: "author name",
    price: 25,
    inventory: 300,
    description:
      "Esta historia está pensada para aquellos que son testigos de conflictos y/o bullying, y que necesitan ser valientes para decir “NO” frente a situaciones injustas, y poder frenar una problemática que es preocupante a nivel mundial. Para poder hacerlo, es clave el desarrollo de habilidades socioemocionales que se adquieren en las relaciones interpersonales. Es necesario trabajar la empatía y el compañerismo con los niños desde la primera infancia, para poder prevenir este tipo de",
  },
  {
    id: 28,
    img: "https://m.media-amazon.com/images/I/41pCPwfC0JL._MCnd_AC_.jpg",
    type: "Best Sellers",
    name: "book name",
    author: "author name",
    price: 25,
    inventory: 300,
    description:
      "Esta historia está pensada para aquellos que son testigos de conflictos y/o bullying, y que necesitan ser valientes para decir “NO” frente a situaciones injustas, y poder frenar una problemática que es preocupante a nivel mundial. Para poder hacerlo, es clave el desarrollo de habilidades socioemocionales que se adquieren en las relaciones interpersonales. Es necesario trabajar la empatía y el compañerismo con los niños desde la primera infancia, para poder prevenir este tipo de",
  },
  {
    id: 29,
    img: "https://m.media-amazon.com/images/I/41Jaz-UzAjL._MCnd_AC_.jpg",
    type: "Best Sellers",
    name: "book name",
    author: "author name",
    price: 25,
    inventory: 300,
    description:
      "Esta historia está pensada para aquellos que son testigos de conflictos y/o bullying, y que necesitan ser valientes para decir “NO” frente a situaciones injustas, y poder frenar una problemática que es preocupante a nivel mundial. Para poder hacerlo, es clave el desarrollo de habilidades socioemocionales que se adquieren en las relaciones interpersonales. Es necesario trabajar la empatía y el compañerismo con los niños desde la primera infancia, para poder prevenir este tipo de",
  },
  {
    id: 30,
    img: "https://m.media-amazon.com/images/I/51xrHMLGJPL._MCnd_AC_.jpg",
    type: "Best Sellers",
    name: "book name",
    author: "author name",
    price: 25,
    inventory: 300,
    description:
      "Esta historia está pensada para aquellos que son testigos de conflictos y/o bullying, y que necesitan ser valientes para decir “NO” frente a situaciones injustas, y poder frenar una problemática que es preocupante a nivel mundial. Para poder hacerlo, es clave el desarrollo de habilidades socioemocionales que se adquieren en las relaciones interpersonales. Es necesario trabajar la empatía y el compañerismo con los niños desde la primera infancia, para poder prevenir este tipo de",
  },
  {
    id: 31,
    img: "https://m.media-amazon.com/images/I/51yoHjJDQ3L._MCnd_AC_.jpg",
    type: "Best Sellers",
    name: "book name",
    author: "author name",
    price: 25,
    inventory: 300,
    description:
      "Esta historia está pensada para aquellos que son testigos de conflictos y/o bullying, y que necesitan ser valientes para decir “NO” frente a situaciones injustas, y poder frenar una problemática que es preocupante a nivel mundial. Para poder hacerlo, es clave el desarrollo de habilidades socioemocionales que se adquieren en las relaciones interpersonales. Es necesario trabajar la empatía y el compañerismo con los niños desde la primera infancia, para poder prevenir este tipo de",
  },
  {
    id: 32,
    img: "https://m.media-amazon.com/images/I/41eCN7506VL._MCnd_AC_.jpg",
    type: "Best Sellers",
    name: "book name",
    author: "author name",
    price: 25,
    inventory: 300,
    description:
      "Esta historia está pensada para aquellos que son testigos de conflictos y/o bullying, y que necesitan ser valientes para decir “NO” frente a situaciones injustas, y poder frenar una problemática que es preocupante a nivel mundial. Para poder hacerlo, es clave el desarrollo de habilidades socioemocionales que se adquieren en las relaciones interpersonales. Es necesario trabajar la empatía y el compañerismo con los niños desde la primera infancia, para poder prevenir este tipo de",
  },
  {
    id: 33,
    img: "https://m.media-amazon.com/images/I/51C1EdbZwLL._MCnd_AC_.jpg",
    type: "Best Sellers",
    name: "book name",
    author: "author name",
    price: 25,
    inventory: 300,
    description:
      "Esta historia está pensada para aquellos que son testigos de conflictos y/o bullying, y que necesitan ser valientes para decir “NO” frente a situaciones injustas, y poder frenar una problemática que es preocupante a nivel mundial. Para poder hacerlo, es clave el desarrollo de habilidades socioemocionales que se adquieren en las relaciones interpersonales. Es necesario trabajar la empatía y el compañerismo con los niños desde la primera infancia, para poder prevenir este tipo de",
  },
  {
    id: 34,
    img: "https://m.media-amazon.com/images/I/510Y57m6XJL._MCnd_AC_.jpg",
    type: "Best Sellers",
    name: "book name",
    author: "author name",
    price: 25,
    inventory: 300,
    description:
      "Esta historia está pensada para aquellos que son testigos de conflictos y/o bullying, y que necesitan ser valientes para decir “NO” frente a situaciones injustas, y poder frenar una problemática que es preocupante a nivel mundial. Para poder hacerlo, es clave el desarrollo de habilidades socioemocionales que se adquieren en las relaciones interpersonales. Es necesario trabajar la empatía y el compañerismo con los niños desde la primera infancia, para poder prevenir este tipo de",
  },
  {
    id: 35,
    img: "https://m.media-amazon.com/images/I/41cI+KjAjtL._MCnd_AC_.jpg",
    type: "Best Sellers",
    name: "book name",
    author: "author name",
    price: 25,
    inventory: 300,
    description:
      "Esta historia está pensada para aquellos que son testigos de conflictos y/o bullying, y que necesitan ser valientes para decir “NO” frente a situaciones injustas, y poder frenar una problemática que es preocupante a nivel mundial. Para poder hacerlo, es clave el desarrollo de habilidades socioemocionales que se adquieren en las relaciones interpersonales. Es necesario trabajar la empatía y el compañerismo con los niños desde la primera infancia, para poder prevenir este tipo de",
  },
  {
    id: 36,
    img: "https://m.media-amazon.com/images/I/51i8VUx2ztL._SX218_BO1,204,203,200_QL40_FMwebp_.jpg",
    type: "Children's Books",
    name: "book name",
    author: "author name",
    price: 25,
    inventory: 300,
    description:
      "Esta historia está pensada para aquellos que son testigos de conflictos y/o bullying, y que necesitan ser valientes para decir “NO” frente a situaciones injustas, y poder frenar una problemática que es preocupante a nivel mundial. Para poder hacerlo, es clave el desarrollo de habilidades socioemocionales que se adquieren en las relaciones interpersonales. Es necesario trabajar la empatía y el compañerismo con los niños desde la primera infancia, para poder prevenir este tipo de",
  },
  {
    id: 37,
    img: "https://m.media-amazon.com/images/I/51p2SDOCV9L._SX218_BO1,204,203,200_QL40_FMwebp_.jpg",
    type: "Children's Books",
    name: "book name",
    author: "author name",
    price: 25,
    inventory: 300,
    description:
      "Esta historia está pensada para aquellos que son testigos de conflictos y/o bullying, y que necesitan ser valientes para decir “NO” frente a situaciones injustas, y poder frenar una problemática que es preocupante a nivel mundial. Para poder hacerlo, es clave el desarrollo de habilidades socioemocionales que se adquieren en las relaciones interpersonales. Es necesario trabajar la empatía y el compañerismo con los niños desde la primera infancia, para poder prevenir este tipo de",
  },
  {
    id: 38,
    img: "https://m.media-amazon.com/images/I/61YB0a1YfBL.jpg",
    type: "Children's Books",
    name: "book name",
    author: "author name",
    price: 25,
    inventory: 300,
    description:
      "Esta historia está pensada para aquellos que son testigos de conflictos y/o bullying, y que necesitan ser valientes para decir “NO” frente a situaciones injustas, y poder frenar una problemática que es preocupante a nivel mundial. Para poder hacerlo, es clave el desarrollo de habilidades socioemocionales que se adquieren en las relaciones interpersonales. Es necesario trabajar la empatía y el compañerismo con los niños desde la primera infancia, para poder prevenir este tipo de",
  },
  {
    id: 39,
    img: "https://m.media-amazon.com/images/I/51LK1jhb4iL._SX394_BO1,204,203,200_.jpg",
    type: "Children's Books",
    name: "book name",
    author: "author name",
    price: 25,
    inventory: 300,
    description:
      "Esta historia está pensada para aquellos que son testigos de conflictos y/o bullying, y que necesitan ser valientes para decir “NO” frente a situaciones injustas, y poder frenar una problemática que es preocupante a nivel mundial. Para poder hacerlo, es clave el desarrollo de habilidades socioemocionales que se adquieren en las relaciones interpersonales. Es necesario trabajar la empatía y el compañerismo con los niños desde la primera infancia, para poder prevenir este tipo de",
  },
  {
    id: 40,
    img: "https://m.media-amazon.com/images/I/51XYT80GuNL._AC_UF420%2C420_FMjpg_.jpg",
    type: "Children's Books",
    name: "book name",
    author: "author name",
    price: 25,
    inventory: 300,
    description:
      "Esta historia está pensada para aquellos que son testigos de conflictos y/o bullying, y que necesitan ser valientes para decir “NO” frente a situaciones injustas, y poder frenar una problemática que es preocupante a nivel mundial. Para poder hacerlo, es clave el desarrollo de habilidades socioemocionales que se adquieren en las relaciones interpersonales. Es necesario trabajar la empatía y el compañerismo con los niños desde la primera infancia, para poder prevenir este tipo de",
  },
  {
    id: 41,
    img: "https://m.media-amazon.com/images/I/61i5xNzX4tL._AC_UF420%2C420_FMjpg_.jpg",
    type: "Children's Books",
    name: "book name",
    author: "author name",
    price: 25,
    inventory: 300,
    description:
      "Esta historia está pensada para aquellos que son testigos de conflictos y/o bullying, y que necesitan ser valientes para decir “NO” frente a situaciones injustas, y poder frenar una problemática que es preocupante a nivel mundial. Para poder hacerlo, es clave el desarrollo de habilidades socioemocionales que se adquieren en las relaciones interpersonales. Es necesario trabajar la empatía y el compañerismo con los niños desde la primera infancia, para poder prevenir este tipo de",
  },
  {
    id: 42,
    img: "https://m.media-amazon.com/images/I/61d8CHd8kfL._AC_UF420%2C420_FMjpg_.jpg",
    type: "Children's Books",
    name: "book name",
    author: "author name",
    price: 25,
    inventory: 300,
    description:
      "Esta historia está pensada para aquellos que son testigos de conflictos y/o bullying, y que necesitan ser valientes para decir “NO” frente a situaciones injustas, y poder frenar una problemática que es preocupante a nivel mundial. Para poder hacerlo, es clave el desarrollo de habilidades socioemocionales que se adquieren en las relaciones interpersonales. Es necesario trabajar la empatía y el compañerismo con los niños desde la primera infancia, para poder prevenir este tipo de",
  },
];

export default initList;
