const initList = [
  {
    id: 1,
    img: "https://m.media-amazon.com/images/I/613IJTfd4JL._AC_SY200_.jpg",
    type: "book",
  },
  {
    id: 2,
    img: "https://m.media-amazon.com/images/I/61JXmQsaMdL._AC_SY200_.jpg",
    type: "book",
  },
  {
    id: 3,
    img: "https://m.media-amazon.com/images/I/71P7dg0psjL._AC_SY200_.jpg",
    type: "book",
  },
  {
    id: 4,
    img: "https://m.media-amazon.com/images/I/61bPiEPsl4L._AC_SY200_.jpg",
    type: "book",
  },
  {
    id: 5,
    img: "https://m.media-amazon.com/images/I/61sfUlu18JL._AC_SY200_.jpg",
    type: "book",
  },
  {
    id: 6,
    img: "https://m.media-amazon.com/images/I/615D0CB8NOL._AC_SY200_.jpg",
    type: "book",
  },
  {
    id: 7,
    img: "https://m.media-amazon.com/images/I/51iuvBRzq3L._AC_SY200_.jpg",
    type: "book",
  },
  {
    id: 8,
    img: "https://m.media-amazon.com/images/I/61AimGVbY9L._AC_SY200_.jpg",
    type: "book",
  },
  {
    id: 9,
    img: "https://m.media-amazon.com/images/I/61VgZPzVIBL._AC_SY200_.jpg",
    type: "book",
  },
  {
    id: 10,
    img: "https://m.media-amazon.com/images/I/61aVumIonhL._AC_SY200_.jpg",
    type: "book",
  },
  {
    id: 11,
    img: "https://m.media-amazon.com/images/I/41whMkdjtBL._AC_SY200_.jpg",
    type: "book",
  },
  {
    id: 12,
    img: "https://m.media-amazon.com/images/I/61mi9uULrLL._AC_SY200_.jpg",
    type: "book",
  },
  {
    id: 13,
    img: "https://m.media-amazon.com/images/I/61aVumIonhL._AC_SY200_.jpg",
    type: "book",
  },
  {
    id: 14,
    img: "https://m.media-amazon.com/images/I/41whMkdjtBL._AC_SY200_.jpg",
    type: "book",
  },
  {
    id: 15,
    img: "https://m.media-amazon.com/images/I/61mi9uULrLL._AC_SY200_.jpg",
    type: "book",
  },
  {
    id: 16,
    img: "https://m.media-amazon.com/images/I/61mi9uULrLL._AC_SY200_.jpg",
    type: "book",
  },
  {
    id: 17,
    img: "https://m.media-amazon.com/images/I/71b7Hy82JpL._AC_SY200_.jpg",
    type: "book",
  },
  {
    id: 18,
    img: "https://m.media-amazon.com/images/I/61199SIEUbL._AC_SY200_.jpg",
    type: "book",
  },
  {
    id: 19,
    img: "https://m.media-amazon.com/images/I/61S3zhCVkPL._AC_SY200_.jpg",
    type: "book",
  },
  {
    id: 20,
    img: "https://m.media-amazon.com/images/I/61wnXwdvIzL._AC_SY200_.jpg",
    type: "book",
  },
  {
    id: 21,
    img: "https://m.media-amazon.com/images/I/51lfB8o5WQL._AC_SY200_.jpg",
    type: "book",
  },
  {
    id: 22,
    header: "Home refresh ideas",
    name: "",
    more: "Shop kitchen upgrades",
    img: "https://images-na.ssl-images-amazon.com/images/G/01/home/THILGMA/SpringEvent2023/XCM_CUTTLE_1559454_3018199_379x304_1X_en_US._SY304_CB592739737_.jpg",
    type: "productPopular",
  },
  {
    id: 23,
    header: "Create with strip lights",
    name: "",
    more: "Shop now",
    img: "https://images-na.ssl-images-amazon.com/images/G/01/AmazonExports/Fuji/2020/May/Dashboard/Fuji_Dash_StripLighting_379x304_1X_en_US._SY304_CB418597476_.jpg",
    type: "productPopular",
  },
  {
    id: 24,
    header: "Discover fashion trends",
    name: "",
    more: "See more",
    img: "https://images-na.ssl-images-amazon.com/images/G/01/softlines/shopbop/ingress/2023/March/mp_20230219_ff_desktopsinglecategory_desktop_379x304_1._SY304_CB612639047_.jpg",
    type: "productPopular",
  },
  {
    id: 25,
    header: "Shop Laptops & Tablets",
    name: "",
    more: "See more",
    img: "https://images-na.ssl-images-amazon.com/images/G/01/AmazonExports/Fuji/2020/May/Dashboard/Fuji_Dash_Laptops_379x304_1X_en_US._SY304_CB418608471_.jpg",
    type: "productPopular",
  },
  {
    id: 26,
    img: "https://m.media-amazon.com/images/I/51G03DgxVGL._AC_SY200_.jpg",
    type: "internationalTop",
  },
  {
    id: 27,
    img: "https://m.media-amazon.com/images/I/71nhPE7vxHL._AC_SY200_.jpg",
    type: "internationalTop",
  },
  {
    id: 28,
    img: "https://m.media-amazon.com/images/I/41+ggaEDZGL._AC_SY200_.jpg",
    type: "internationalTop",
  },
  {
    id: 29,
    img: "https://m.media-amazon.com/images/I/914E5Qnnp+L._AC_SY200_.jpg",
    type: "internationalTop",
  },
  {
    id: 30,
    img: "https://m.media-amazon.com/images/I/71HesIYMSYL._AC_SY200_.jpg",
    type: "internationalTop",
  },
  {
    id: 31,
    img: "https://m.media-amazon.com/images/I/51k4Z0A6TDL._AC_SY200_.jpg",
    type: "internationalTop",
  },
  {
    id: 32,
    img: "https://m.media-amazon.com/images/I/51gL1uEb9OL._AC_SY200_.jpg",
    type: "internationalTop",
  },
  {
    id: 33,
    header: "Top Deal",
    name: "samsung Galaxy S22 Ultra",
    more: "See all deals",
    img: "https://m.media-amazon.com/images/I/41Te8HXFyjL._AC_SY230_.jpg",
    type: "productTopDeal",
  },
  {
    id: 34,
    header: "Health & Personal Care",
    title: "",
    more: "shop now",
    img: "https://images-na.ssl-images-amazon.com/images/G/01/AmazonExports/Fuji/2022/February/DashboardCards/GW_CONS_AUS_HPC_HPCEssentials_CatCard_Desktop1x._SY304_CB627424361_.jpg",
    type: "productTopDeal",
  },
  {
    id: 35,
    header: "Home & Kitchen Under $30",
    title: "",
    more: "Shop Now",
    img: "https://images-na.ssl-images-amazon.com/images/G/01/US-hq/2022/img/Amazon_Exports/XCM_CUTTLE_1469391_2584745_379x304_1X_en_US._SY304_CB609304299_.jpg",
    type: "productTopDeal",
  },
  {
    id: 36,
    header: "Electronics",
    title: "",
    more: "See more",
    img: "https://images-na.ssl-images-amazon.com/images/G/01/AmazonExports/Fuji/2020/May/Dashboard/Fuji_Dash_Electronics_1x._SY304_CB432774322_.jpg",
    type: "productTopDeal",
  },
  {
    id: 37,
    header: "Toys Under $30",
    name: "",
    more: "Shop now",
    img: "https://images-na.ssl-images-amazon.com/images/G/01/US-hq/2022/img/Amazon_Exports/XCM_CUTTLE_1469244_2584128_379x304_1X_en_US._SY304_CB609318944_.jpg",
    type: "productTopDeal",
  },
  {
    id: 38,
    header: "Shop deals in Fashion",
    title: "",
    more: "See all deals",
    img: "https://images-na.ssl-images-amazon.com/images/G/01/AMAZON_FASHION/2022/SITE_FLIPS/SPR_22/GW/DQC/DQC_APR_TBYB_W_BOTTOMS_1x._SY116_CB624172947_.jpg",
    type: "productTopDeal",
  },
  {
    id: 39,
    header: "Fashion trends you like",
    title: "",
    more: "Explore more",
    img: "https://images-na.ssl-images-amazon.com/images/G/01/AMAZON_FASHION/2023/LuxuryStores/Spring-23/GW/Quad_Cards/Spring/LSS23_SPRING_DT_CAT_CARD_1_x1._SY116_CB595261253_.jpg",
    type: "productTopDeal",
  },
  {
    id: 40,
    header: "Get fit at home",
    title: "",
    more: "Explore now",
    img: "https://images-na.ssl-images-amazon.com/images/G/01/events/GFAH/GWDesktop_SingleImageCard_fitathome_1x._SY304_CB434924743_.jpg",
    type: "productTopDeal",
  },
  {
    id: 41,
    img: "https://m.media-amazon.com/images/I/71TAYmz9znL._AC_SY200_.jpg",
    type: "skinCareProduct",
  },
  {
    id: 42,
    img: "https://m.media-amazon.com/images/I/71-GCIBN8wL._AC_SY200_.jpg",
    type: "skinCareProduct",
  },
  {
    id: 43,
    img: "https://m.media-amazon.com/images/I/71UH7m3ORSL._AC_SY200_.jpg",
    type: "skinCareProduct",
  },
  {
    id: 44,
    img: "https://m.media-amazon.com/images/I/71Pla6Or7VL._AC_SY200_.jpg",
    type: "skinCareProduct",
  },
  {
    id: 45,
    img: "https://m.media-amazon.com/images/I/61iPbqQvEHL._AC_SY200_.jpg",
    type: "skinCareProduct",
  },
  {
    id: 46,
    img: "https://m.media-amazon.com/images/I/61UcS1QVdFS._AC_SY200_.jpg",
    type: "skinCareProduct",
  },
  {
    id: 47,
    img: "https://m.media-amazon.com/images/I/519yulXccRL._AC_SY200_.jpg",
    type: "skinCareProduct",
  },
  {
    id: 48,
    img: "https://m.media-amazon.com/images/I/71yvkPOVPoL._AC_SY200_.jpg",
    type: "skinCareProduct",
  },
  {
    id: 49,
    img: "https://m.media-amazon.com/images/I/81edK5givrL._AC_SY200_.jpg",
    type: "skinCareProduct",
  },
  {
    id: 50,
    img: "https://m.media-amazon.com/images/I/61VzSDlgfiL._AC_SY200_.jpg",
    type: "skinCareProduct",
  },
  {
    id: 51,
    img: "https://m.media-amazon.com/images/I/61YCTFZYjlL._AC_SY200_.jpg",
    type: "skinCareProduct",
  },
  {
    id: 52,
    img: "https://m.media-amazon.com/images/I/71o+VkzzCIL._AC_SY200_.jpg",
    type: "skinCareProduct",
  },
  {
    id: 53,
    img: "https://m.media-amazon.com/images/I/71eK0jULmVL._AC_SY200_.jpg",
    type: "skinCareProduct",
  },
  {
    id: 54,
    img: "https://m.media-amazon.com/images/I/41lnke7idrL._AC_SY200_.jpg",
    type: "skinCareProduct",
  },
  {
    id: 55,
    img: "https://m.media-amazon.com/images/I/61oYUTKeCLL._AC_SY200_.jpg",
    type: "skinCareProduct",
  },
  {
    id: 56,
    img: "https://m.media-amazon.com/images/I/71eYtnCQuhL._AC_SY200_.jpg",
    type: "skinCareProduct",
  },
];

export default initList;
